---
- name: Remove not-in-use packages
  community.general.flatpak:
    name:
      - com.logseq.Logseq
      - fyi.zoey.TeX-Match  # find latex symbols, uses end-of-life library (org.freedesktop.Platform 22.08) (2024-11-06)
      - info.smplayer.SMPlayer
      - io.github.celluloid_player.Celluloid  # NOTE: celluloid is very slow  <2024-12-15>
      - org.kde.kamoso  # theora 로 녹화하는데, 코덱 선택을 할수가 없음. <2025-09-22>
      - org.gnome.gitlab.YaLTeR.Identity
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.kde.kontact
      # Dev
      - com.getpostman.Postman  # Proprietary
      - dev.pulsar_edit.Pulsar  # editor, mit
      - io.httpie.Httpie  # Proprietary
      - org.gnome.gitlab.cheywood.Buffer  # empty editor
      - rest.insomnia.Insomnia  # mit
      #
      - md.obsidian.Obsidian  # flatpak 패키지를 사용하면 ime autoswitch 가 작동 하지 않음. <2025-10>
    state: absent
    method: user
