---
# See: https://pre-commit.com/
repos:
  - repo: local
    hooks:
      - id: stylua
        name: format lua
        entry: stylua
        language: system
        types: [lua]
      - id: taplo
        name: format toml
        entry: taplo format
        language: system
        types: [toml]
